version: '3'

volumes:
  foodgram_data:
  static:

services:
  foodgram_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - foodgram_db
  frontend:
    env_file: .env
    build: ./frontend/
  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    ports:
      - 8080:80
    depends_on:
      - backend
