# Generated by Django 3.2.3 on 2023-12-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231216_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useruser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
