# Generated by Django 3.2.3 on 2023-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useruser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
